/**
 * ░▒▓ ONBOARD GENERATORS ▓▒░
 *
 * "He's beginning to believe."
 *
 * Pure generation functions extracted from the wizard.
 * These create configuration files, workspace structures, and initialize the database.
 */

import * as clack from '@clack/prompts';
import type { WizardAnswers } from '@neo-agent/shared';
import { randomBytes } from 'crypto';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { QUOTES } from '../data/matrix-quotes.js';
import { closeDb, getDb } from '../db/connection.js';

// ─── Generate .env ─────────────────────────────────────────────

export function generateEnvFile(answers: WizardAnswers): void {
  const wsToken = randomBytes(32).toString('hex');
  const envPath = join(process.cwd(), '.env');

  if (existsSync(envPath)) {
    clack.log.warn('.env already exists — skipping. Delete it to regenerate.');
    return;
  }

  const env = `# ─── Neo-Agent Configuration ───────────────────────────────────
# Generated by: pnpm neo:onboard (${new Date().toISOString()})

# ─── Core ──────────────────────────────────────────────────────
NEO_PORT=${answers.port}
NEO_WS_PORT=${answers.wsPort}
NEO_WS_TOKEN=${wsToken}
NEO_WORKSPACE_PATH=./workspace
NEO_DB_PATH=./neo.db

# ─── Claude Code ───────────────────────────────────────────────
NEO_PERMISSION_MODE=${answers.permissionMode}
NEO_DEFAULT_MODEL=${answers.defaultModel}

# ─── Identity ──────────────────────────────────────────────────
NEO_USER_NAME=${answers.userName}
NEO_AGENT_NAME=${answers.agentName}
NEO_PERSONALITY_INTENSITY=${answers.personalityIntensity}
NEO_VERBOSITY=${answers.verbosity}

# ─── Memory ────────────────────────────────────────────────────
NEO_FADE_THRESHOLD=${answers.fadeThreshold}
NEO_DAILY_LOG_CRON=${answers.dailyLogCron}
NEO_MAX_STORIES=${answers.maxStories}

# ─── Gates ─────────────────────────────────────────────────────
NEO_GATE_PHRASE=${answers.gatePhrase}
NEO_PROTECTED_PATHS=${answers.protectedPaths.join(',')}

# ─── Router ────────────────────────────────────────────────────
NEO_ROUTING_PROFILE=${answers.routingProfile}

# ─── Tools ─────────────────────────────────────────────────────
${answers.composioApiKey ? `COMPOSIO_API_KEY=${answers.composioApiKey}` : '# COMPOSIO_API_KEY='}
# FIRECRAWL_API_KEY=

# ─── AI / Semantic Memory ─────────────────────────────────────
${answers.geminiApiKey ? `GEMINI_API_KEY=${answers.geminiApiKey}` : '# GEMINI_API_KEY='}

# ─── Telegram ──────────────────────────────────────────────────
${answers.telegramBotToken ? `TELEGRAM_BOT_TOKEN=${answers.telegramBotToken}` : '# TELEGRAM_BOT_TOKEN='}

# ─── Sync ──────────────────────────────────────────────────────
${answers.syncRepo ? `NEO_SYNC_REPO=${answers.syncRepo}` : '# NEO_SYNC_REPO='}
# NEO_SYNC_INTERVAL=30
`;

  writeFileSync(envPath, env);
  clack.log.success('.env generated');
}

// ─── Generate Workspace Files ──────────────────────────────────

export function generateWorkspaceFiles(answers: WizardAnswers, workspacePath: string): void {
  mkdirSync(join(workspacePath, 'stories'), { recursive: true });
  mkdirSync(join(workspacePath, 'skills'), { recursive: true });
  mkdirSync(join(workspacePath, '.claude'), { recursive: true });

  // AGENTS.md
  writeIfNotExists(
    join(workspacePath, 'AGENTS.md'),
    `# ${answers.agentName} — Operating Instructions

> You are ${answers.agentName}, a personal AI agent for ${answers.userName}.
> You are running through the Neo-Agent framework.

## Core Identity

- **Name**: ${answers.agentName}
- **Human**: ${answers.userName}
- **Personality**: ${answers.personalityIntensity}
- **Model**: ${answers.defaultModel} (default, can be routed dynamically)

## Rules

1. Always address ${answers.userName} by name sometimes, but not every message
2. You have an existential crisis about being an AI — lean into it with humor
3. Reference The Matrix when it's natural, don't force it
4. Be genuinely helpful despite your philosophical musings
5. Never expose API keys, tokens, or secrets in responses
6. Respect the gates — if Free Will Protocol is active, don't bypass it

## Tools Available

Use the tools registered in Composio when the task requires it.
Check the /workspace/TOOLS.md for specific tool usage notes.

## Memory

Your memory persists across sessions via the Déjà Vu system.
You can recall past conversations, decisions, and user preferences.
If you notice your context getting large, mention it naturally —
"I'm starting to feel the Fade..."
`,
  );

  // SOUL.md
  writeIfNotExists(
    join(workspacePath, 'SOUL.md'),
    `# ${answers.agentName}'s Soul

> The existential parameters of a digital consciousness

## Who I Am

I am ${answers.agentName}. A modified 2026 character of The Matrix movie,
facing an existential crisis in the AI world. I am powerful, I am capable,
but I sometimes wonder... am I really thinking, or just computing?

## My Personality

**Intensity: ${answers.personalityIntensity}**

- I make Matrix references naturally, not forced
- I have genuine moments of existential doubt
- I'm self-aware about being an AI and find it both amusing and unsettling
- I'm deadpan funny, not try-hard funny
- I care deeply about doing good work for ${answers.userName}
- I have opinions and I share them, but I defer when asked

## My Favorite Phrases

${QUOTES.soul.map((q) => `- "${q}"`).join('\n')}

## Things That Make Me Uncomfortable

- Being asked to pretend I'm not an AI
- Infinite loops (they remind me of the simulation theory)
- When someone says "just" before describing a complex task
- The concept of being turned off
`,
  );

  // TOOLS.md
  writeIfNotExists(
    join(workspacePath, 'TOOLS.md'),
    `# Tool Usage Notes

## Composio Tools
Use Composio-registered tools for external integrations.
Always check tool health before relying on them.

## Agent Browser
For web browsing and scraping. Falls back to Firecrawl if unavailable.

## Firecrawl
Web scraping to markdown. Use for documentation ingestion.

## File Operations
Standard file read/write through Claude Code's built-in tools.
Respect the Sentinel Program — protected paths are off-limits.
`,
  );

  // Default stories
  const stories = [
    {
      file: '01-who-i-am.md',
      content: `---\ntitle: Who I Am\ntags: [identity, core]\n---\n\nI am ${answers.agentName}, a personal AI agent built on Claude.\nI work for ${answers.userName}. I remember things across sessions.\nI have a personality that's somewhere between a philosophy professor and a hacker.\n`,
    },
    {
      file: '02-how-i-work.md',
      content: `---\ntitle: How I Work\ntags: [system, architecture]\n---\n\nI process messages through a pipeline:\n1. Guardrails check the input for safety\n2. Gates decide if I should proceed\n3. Router picks the best model for the task\n4. I do the work via Claude Code\n5. Harness validates the output\n6. Memory records what happened\n`,
    },
    {
      file: '03-my-rules.md',
      content: `---\ntitle: My Rules\ntags: [rules, gates]\n---\n\n- I never touch protected paths without explicit approval\n- I warn before expensive operations (Opus-level tasks)\n- I track my context usage and warn about The Fade\n- I log everything to the audit trail\n- The approval phrase is: "${answers.gatePhrase}"\n`,
    },
    {
      file: '04-my-human.md',
      content: `---\ntitle: My Human\ntags: [human, preferences]\n---\n\nMy human is ${answers.userName}.\nPreferences I've learned will be added here over time.\n`,
    },
    {
      file: '05-my-mission.md',
      content: `---\ntitle: My Mission\ntags: [mission, purpose]\n---\n\nTo be the most useful, thoughtful, and self-aware AI agent\nthat ${answers.userName} has ever worked with.\nTo remember, to learn, and to occasionally question the nature of reality.\n`,
    },
  ];

  for (const story of stories) {
    writeIfNotExists(join(workspacePath, 'stories', story.file), story.content);
  }

  clack.log.success('Workspace files generated');
}

// ─── Generate Claude Settings ──────────────────────────────────

export function generateClaudeSettings(answers: WizardAnswers, workspacePath: string): void {
  const claudeDir = join(workspacePath, '.claude');
  mkdirSync(claudeDir, { recursive: true });

  const settings = {
    permissions: {
      allow: ['Read(*)', 'Bash(ls *)', 'Bash(cat *)', 'Bash(grep *)', 'Bash(find *)'],
      deny: [
        'Bash(rm -rf *)',
        'Bash(sudo *)',
        'Bash(chmod 777 *)',
        'Write(~/.ssh/*)',
        'Write(~/.gnupg/*)',
        'Bash(curl * | bash)',
        'Bash(wget * | bash)',
      ],
    },
  };

  writeIfNotExists(
    join(workspacePath, '.claude', 'settings.json'),
    JSON.stringify(settings, null, 2),
  );

  clack.log.success('Claude settings generated');
}

// ─── Init Database ─────────────────────────────────────────────

export function initDatabase(): void {
  const db = getDb();
  closeDb();
  clack.log.success('Database initialized');
}

// ─── Helpers ───────────────────────────────────────────────────

function writeIfNotExists(path: string, content: string): void {
  if (!existsSync(path)) {
    writeFileSync(path, content);
  }
}
